Fix drop behavior #11
RazrFalcon/rctree pull request #20
Opened 2023-02-19 11:11 UTC by tajtiattila

This change should fix the `Drop` issue in #11.

There is also a new test drop_keeps_strong_refs to verify the expected behavior.

2023-02-19 14:59 UTC, RazrFalcon requested changes

2023-02-19 14:59 UTC, RazrFalcon commented on src/lib.rs
> -        // Collect all descendant nodes and detach them to prevent the stack overflow.
I think you should keep this comment. Otherwise it's not clear why we need a custom Drop.

2023-02-19 14:59 UTC, RazrFalcon commented on src/lib.rs
> +    let mut work = vec![node];
`work` is a weird name. Maybe we should use something like `remaining`?

2023-02-19 15:00 UTC, RazrFalcon requested changes

2023-02-19 15:00 UTC, RazrFalcon commented on src/lib.rs
> +fn detach_all_unique<T>(node: Link<T>) {
Do we need a separate method? We can keep it inside Drop.

2023-02-19 15:01 UTC, RazrFalcon commented
So if I understood correctly, the main change here is that only uniquely owned nodes are dropped now, right? There are no other changes.

2023-02-19 18:25 UTC, tajtiattila commented on src/lib.rs
> -        // Collect all descendant nodes and detach them to prevent the stack overflow.
Agreed.

2023-02-19 18:25 UTC, tajtiattila commented on src/lib.rs
> +    let mut work = vec![node];
It holds nodes to be processed, but I agree we should try to find a better name. Maybe `open` or `open_set` as in the set of items to check? The Wikipedia page for the A* search algorithm uses that. The old method used `stack` that could also work here.

2023-02-19 18:25 UTC, tajtiattila commented on src/lib.rs
> +fn detach_all_unique<T>(node: Link<T>) {
Yep, not needed. I was still thinking if detach_all_unique needs to be called for the `next_sibling` at the time of writing.

2023-02-20 15:38 UTC, RazrFalcon approved these changes

2023-02-20 15:39 UTC, merged